[package]
name = "nodeflux-assignment"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"